libriscv/libriscv

- emulator/src/main.cpp
- lib/CMakeLists.txt
- lib/libriscv/linux/system_calls.cpp
- lib/libriscv/posix_filedesc.hpp
- lib/libriscv/rsp_server.hpp
- lib/libriscv/socket_calls.cpp
- lib/libriscv/win32/rsp_server.hpp
- lib/libriscv/win32/system_calls.cpp
- lib/libriscv/win32/ws2.hpp
Added Windows compatibility with MinGW as compiler. (MSVC doesn't work)
All syscalls are implemented except for:
- syscall_dup (for sockets)
- syscall_openat, syscall_readlinkat, syscall_fstatat
- syscall_ioctl, syscall_fcntl
- syscall_statx
Sockets work with winsock2.
Fixes https://github.com/fwsGonzo/libriscv/issues/40
> Fix Windows compatibility

- .github/workflows/unittests_exp.yml
- lib/CMakeLists.txt
- lib/libriscv/common.hpp
- lib/libriscv/cpu.cpp
- lib/libriscv/cpu.hpp
- lib/libriscv/decoder_cache.cpp
- lib/libriscv/decoder_cache.hpp
- lib/libriscv/multiprocessing.cpp
- tests/unit/heaptest.cpp
- tests/unit/run_experimentally.sh
This mode tries to create sequential runnable sequences that can be run extremely fast, while certain conditions are true.
This mode is 25-33% faster than the second fastest mode, and although not close to binary translation, it is 2x faster than the simulator with the instruction cache disabled.
> Experimental Fast Simulator mode

- lib/libriscv/memory.hpp
- lib/libriscv/page.hpp
Resolves problems with llvm-mingw. The errors are fixed, but not the warnings.
```
cd emulator
mkdir cd build
cd build
cmake .. -GNinja
ninja
C:/Users/elee/Downloads/libriscv/lib/libriscv/page.hpp:34:32: error: implicit instantiation of undefined template 'std::array<unsigned char, 4096>'       
std::array<uint8_t, PageSize> buffer8;
C:/Users/elee/Downloads/libriscv/lib/./libriscv/memory.hpp:216:8: error: no template named 'unordered_map' in namespace 'std'
std::unordered_map<address_t, Page> m_pages;
~~~~~^
```
2 errors generated.
> Resolve clang errors.

- lib/CMakeLists.txt
Test for private pthreads.
Concludes Fix: https://github.com/fwsGonzo/libriscv/issues/62.
> Restore RISCV_MULTIPROCESS

- lib/libriscv/linux/system_calls.cpp
Hello, BSDs will fail with `linux/system_calls.cpp`.
With this change I got libriscv built on OpenBSD and the micro tests are passed.
> Fix build on OpenBSD

- lib/libriscv/machine.hpp
- lib/libriscv/rvi_instr.cpp
- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_api.hpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
- lib/libriscv/tr_types.hpp
- lib/libriscv/types.hpp
Binary translation improvements that aims to improve performance and B-extension support
C-extension is still out of the question, but it would be nice to support the already supported B-extension instructions in order to avoid weird simulation bugs. It has always been the case that binary translation has been a little bit wonky, but it is now starting to feel robust and reliable. Already running the DOOM example at less CPU% than regular interpreter.
> Use real instruction count to avoid exiting binary translation loops

- docs/VMCALL.md
- examples/doom/src/main.cpp
- lib/libriscv/cpu.hpp
- lib/libriscv/cpu_dispatch.cpp
- lib/libriscv/instruction_counter.hpp
- lib/libriscv/machine.hpp
- lib/libriscv/machine_inline.hpp
- lib/libriscv/machine_vmcall.hpp
- lib/libriscv/tailcall_dispatch.cpp
- tests/unit/micro.cpp
This is in an effort to reduce the load on the simulate() function at the beginning, but no noticable improvement. Also, added a resume() function and made preempt() instruction counting more explicit.
> Pass instruction counters in registers to simulate()

- lib/libriscv/cpu_dispatch.cpp
- lib/libriscv/decoded_exec_segment.hpp
- lib/libriscv/instruction_counter.hpp
- lib/libriscv/tailcall_dispatch.cpp
- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
- lib/libriscv/types.hpp
The brutal tests will not pass with binary translation with the first two commits, as something is desynched.
> Use registers for counters when entering and leaving binary translation

- README.md
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
- lib/libriscv/tr_types.hpp
This tiny change increases CoreMark score to 12.6k, ~33% of native performance
> Use a set of global jumps to get more function entry mappings

- lib/libriscv/machine_vmcall.hpp
- tests/unit/vmcall.cpp
This adds 64-bit floating point to vmcall argument list. Should have been done a long time ago, but I guess it was never used by anything until now. I don't particularly like 64-bit FP for gaming, but for long-distance location vectors it was necessary.
> Add missing double type to vmcall fold

- README.md
- lib/libriscv/common.hpp
- lib/libriscv/registers.hpp
- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
Nanboxing can still be (always) enabled with `RISCV_ALWAYS_NANBOXING`.
> Make nanboxing optional

- emulator/mingw_build.sh
- emulator/src/main.cpp
- lib/CMakeLists.txt
- lib/libriscv/common.hpp
- lib/libriscv/decoded_exec_segment.hpp
- lib/libriscv/decoder_cache.cpp
- lib/libriscv/tr_compiler.cpp
- lib/libriscv/tr_translate.cpp
- lib/libriscv/win32/dlfcn.cpp
- lib/libriscv/win32/dlfcn.h
- lib/libriscv/win32/system_calls.cpp
This is the initial support for loading binary translation DLLs on Windows. https://github.com/fwsGonzo/libriscv/issues/136
```
$ VERBOSE=1 wine64 rvlinux.exe ../../binaries/stream-rv64gc 
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
005c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
005c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0064:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0064:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
006c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
006c:fixme:font:get_name_record_codepage encoding 20 not …
```
> Add support for loading binary translated DLLs in MinGW

- lib/libriscv/decoder_cache.cpp
- lib/libriscv/decoder_cache.hpp
- lib/libriscv/memory.cpp
- lib/libriscv/memory.hpp
- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_api.hpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
This PR solves a long-standing issue with binary translation, multiple shared objects and dlopen(). `static` variables are no longer used to store per-machine data, and instead offsets from the CPU is used. All these variables are baked into the checksum of the program, so there will never be a case of Windows players executing an incompatible program. Instead, if it is incompatible, it will just be disregarded.
It also adds a lazy fast-path for unknown instructions, allowing custom instructions to be faster in binary translation. They are lazily resolved in order for the shared object to work even if the order of instruction handlers change, and even for cross-compiled binary translations.
> bintr: Add some PC discoverability to potentially failing paths

- .github/workflows/unittests_bintr.yml
- .github/workflows/unittests_exp.yml
- .github/workflows/unittests_threaded.yml
- lib/libriscv/common.hpp
- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
- lib/libriscv/tr_types.hpp
- tests/unit/vmcall.cpp
Also, some changes to prevent local-jump to locations outside of the execute-segment.
This change enables executing remote calls into a binary translated machine (with fast-path arena disabled)
> bintr: Allow disabling arena per-program

- lib/libriscv/rva_instr.cpp
- lib/libriscv/rvi_instr.cpp
This PR finalizes some fallback code in order to run 32- and 64-bit RISC-V programs on 32-bit ARM. There are still some warnings left (especially in remote debugging), but the CLI is running nicely.
> Build and run test programs on 32-bit ARM

- emulator/CMakeLists.txt
- emulator/README.md
- emulator/src/main.cpp
Much nicer than options through getenv
```
Usage: ./rvlinux [options] <program> [args]
Options:
-h, --help         Print this help message
-v, --verbose      Enable verbose loader output
-d, --debug        Enable CLI debugger
-f, --fuel         Set max instructions until program halts
-g, --gdb          Start GDB server on port 2159
-s, --silent       Suppress program completion information
-t, --timing       Enable timing information in binary translator
-T, --trace        Enable tracing in binary translator
-n, --no-translate Disable binary translation
-m, --mingw        Cross-compile for Windows (MinGW)
-F, --from-start   Start debugger from the beginning (_start)
-S  --sandbox      Enable strict sandbox
```
> Add support for long arguments to CLI

- lib/libriscv/common.hpp
- lib/libriscv/cpu_dispatch.cpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
Try to quickly re-enter binary translation. This change makes a lot of sense now that larger portions of the program is binary translated. Also fix a bug with memory traps and binary translation fallback reads/writes.
> bintr: Try to re-enter translation immediately

- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_emit.cpp
This will likely help TCC and -O0 performance a bit
> bintr: Convert jump() to JUMP_TO() macro

- .github/workflows/bintr.yml
- .github/workflows/packaging_libtcc.yml
- .github/workflows/unittests_libtcc.yml
- .gitignore
- Dockerfile
- emulator/build.sh
- lib/CMakeLists.txt
- lib/libriscv/machine_defaults.cpp
- lib/libriscv/tr_tcc.cpp
- lib/libriscv/tr_translate.cpp
- lib/libriscv_libtcc.pc.in
This PR attempts to fully embed libtcc in the build process, so that it doesn't have to be installed as a system package. It's WIP and won't work with the installed version of libriscv yet.
For now the goal is just to see if it passes the test suite.
> bintr: Embed libtcc properly and build libtcc1.a

- lib/CMakeLists.txt
- lib/libriscv/common.hpp
- lib/libriscv/memory.cpp
- lib/libriscv/memory.hpp
- lib/libriscv/memory_inline.hpp
- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
- lib/libriscv_settings.h.in
The initial code to map the entire 4GB address space for 32-bit guests in order to avoid bound-checks on memory reads and writes. So far the performance increase is fairly modest, < 10%.
```
$ VERBOSE=1 ./rvlinux -v ~/github/coremark/coremark-rv32g_b 
* Loading program of size 75145 from 0x7f6ba52ec010 to virtual 0x10000
* Program segment readable: 1 writable: 0  executable: 1
* Loading program of size 1864 from 0x7f6ba52fe59c to virtual 0x2358c
* Program segment readable: 1 writable: 1  executable: 0
* Entry is at 0x109f4
2K performance run parameters for coremark.
CoreMark Size    : 666
Total ticks      : 14508
Total time (secs): 14.508000
Iterations/Sec   : 20678.246485
Iterations       : 300000
Compiler version : GCC13.2.0
Compiler flags   : -O3 -DPERFORMANCE_RUN=1  
Memory location …
```
> Add experimental unbounded 32-bit arena support

- lib/CMakeLists.txt
- lib/libriscv/cpu.cpp
- lib/libriscv/cpu.hpp
- lib/libriscv/cpu_inline.hpp
- lib/libriscv/decoded_exec_segment.hpp
- lib/libriscv/decoder_cache.cpp
- lib/libriscv/memory.cpp
- lib/libriscv/memory.hpp
- lib/libriscv/memory_rw.cpp
- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
With the JIT-compilation feature it now makes more sense to have it enabled while iterating on code. However, if you have, say, 30 emulators all running the same programs, none of them are currently sharing those segments. On idea to solve this was to make some kind of light forking constructor. Instead, I thought it would be nice if it was fully automatic. So, instead I will make execute segments shared and create a structure with serialized access that maintains known execute segments by simple atomic reference counting. So, if an emulator is providing an execute segment, it will count as 2, while if one emulator is loaning it, it will count as 1. It should all count down to zero in the end.
As a drawback, the TCC memory optimization I made earlier today must now be undone. It makes …
> Make all execute segments backed by shared_ptr

- README.md
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
While this change obviously makes benchmarks look very good, it will probably introduce latency - it's just a matter of discovering what the pros/cons are
> bintr: Avoid exiting bintr by translating entire program

- lib/libriscv/tr_emit.cpp
This missed a few optimizations, and crucially fixes performance with script functions
> bintr: Add missing re-entry after JALR

- lib/CMakeLists.txt
- lib/libriscv/prepared_call.hpp
- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_api.hpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
An attempt at short-circuiting binary translated functions when directly called
The current prepared calls are designed such that they are the most useful to me, but it doesn't seem like they are lowering latency despite clearly "doing less". Very frustrating situation.
> Improved prepared calls

- lib/libriscv/cpu.hpp
- lib/libriscv/cpu_dispatch.cpp
- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_api.hpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_tcc.cpp
- lib/libriscv/tr_translate.cpp
- Handle all exceptions properly
- Store and re-throw actual exception thrown
- Since TCC JIT is ephemeral, use instruction handler indices directly, avoiding decoding
> bintr: Improve TCC execution of unknown instructions

- lib/CMakeLists.txt
- lib/libriscv/common.hpp
- lib/libriscv/cpu_dispatch.cpp
- lib/libriscv/memory.cpp
- lib/libriscv/memory.hpp
- lib/libriscv/memory_inline.hpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
Expand the 32-bit arena concept to allow any power-of-two. This makes it possible for me to use it in a place where there are a bunch of emulators, each not requiring much memory.
Very experimental!
> Implement N-bit encompassing arena

- lib/libriscv/linux/system_calls.cpp
- lib/libriscv/posix/socket_calls.cpp
- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_translate.cpp
Fix some build issues and testing in a FreeBSD VM.
```
The *best* time for each kernel (excluding the first iteration)
will be used to compute the reported bandwidth.
-------------------------------------------------------------
Your clock granularity/precision appears to be 1 microseconds.
Each test below will take on the order of 10433 microseconds.
(= 10433 clock ticks)
Increase the size of the arrays if this shows that
you are not getting at least 20 clock ticks per test.
-------------------------------------------------------------
WARNING -- The above is only a rough guideline.
For best results, please be sure you know the
precision of your system timer.
-------------------------------------------------------------
Function    Best Rate MB/s  Avg time     Min time     Max time
Copy: …
```
> FreeBSD build

- README.md
- emulator/CMakeLists.txt
- emulator/build.sh
- emulator/src/main.cpp
- lib/libriscv/common.hpp
- lib/libriscv/cpu.cpp
- lib/libriscv/decoded_exec_segment.hpp
- lib/libriscv/machine.cpp
- lib/libriscv/machine.hpp
- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
This allows platforms with no support for dynamic linking to ship with full binary translation performance
```
$ VERBOSE=1 ./rvlinux -v ~/github/coremark/coremark-rv32g_b
* Loading program of size 75145 from 0x7402800d1010 to virtual 0x10000 -> 0x22589
* Program segment readable: 1 writable: 0  executable: 1
* Loading program of size 1864 from 0x7402800e359c to virtual 0x2358c -> 0x23cd4
* Program segment readable: 1 writable: 1  executable: 0
Checking for embedded translations
Found embedded translation for hash 808A7861
* Entry is at 0x109f4
2K performance run parameters for coremark.
CoreMark Size    : 666
Total ticks      : 17261
Total time (secs): 17.261000
Iterations/Sec   : 34760.442616
Iterations       : 600000
Compiler version : GCC13.2.0
Compiler flags   : -O3 …
```
> Add initial support for embedded sandboxed code

- lib/CMakeLists.txt
- lib/libriscv/cpu.hpp
- lib/libriscv/decoded_exec_segment.hpp
- lib/libriscv/tr_compiler.cpp
- lib/libriscv/tr_tcc.cpp
- lib/libriscv/tr_translate.cpp
- lib/libriscv/win32/tr_msvc.cpp
With this PR it is now possible to:
1. Provide full binary translation via embedded code, or...
2. Load full binary translation from shared object, or...
3. JIT-compile using libtcc as last resort
This unifies all 3 translation methods, paving the way for all of them to be default-enabled at some point.
It also enables producing full binary translation in the background, although I'm not sure if I would use it.
> Allow using libtcc and full binary translation at the same time

- emulator/src/main.cpp
- lib/libriscv/common.hpp
- lib/libriscv/cpu.hpp
- lib/libriscv/decoded_exec_segment.hpp
- lib/libriscv/decoder_cache.cpp
- lib/libriscv/decoder_cache.hpp
- lib/libriscv/memory.hpp
- lib/libriscv/tr_translate.cpp
- A new callback can be set where you (the user) receives an opaque function that performs the compilation step
- Once the compilation completes, the results are hot-patched into the execute segment
- Most programs complete before libtcc has a chance to compile the programs, only benchmarks work :) 
In the future, perhaps:
Apply libtcc async, then later apply full binary translation async
> Implement binary translation background compilation feature

- lib/libriscv/cpu.cpp
- lib/libriscv/decoded_exec_segment.hpp
- lib/libriscv/decoder_cache.cpp
- lib/libriscv/memory.hpp
- lib/libriscv/threads.hpp
Also, evict them after switching and avoid binary translating them
This allows running v8 programs with Isolates, JIT-compilation and WebAssembly modules
> v8: Avoid caching execute segments that are likely JIT

- README.md
- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_emit.cpp
Returning from a call now covers the whole block, which is a marginal improvement. CoreMark now reaches 92% of native. Safe sandboxing with instruction counting reaches 81% of native.
> bintr: Optimize JUMP_TO and returning from JAL

- emulator/src/main.cpp
- lib/libriscv/common.hpp
- lib/libriscv/cpu.cpp
- lib/libriscv/cpu.hpp
- lib/libriscv/cpu_dispatch.cpp
- lib/libriscv/cpu_inaccurate_dispatch.cpp
- lib/libriscv/decoder_cache.cpp
- lib/libriscv/linux/system_calls.cpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
- lib/libriscv/tr_types.hpp
This allows running NodeJS to start 2x faster, and allows using faster decoding for main segment
At some point the decoder cache should set up traps so that changes to the execute segment cause it to be come stale and eventually evicted automatically. For now, JIT-segments will just be executed slowly.
```
$ time ./rvlinux -P ../binaries/node -- --jitless test.js
Warning: disabling flag --expose_wasm due to conflicting flags
Node.js says fibonacci(10) = 55
>>> Program exited, exit code = 0 (0x0)
Runtime: 926.901ms   (Use --accurate for instruction counting)
Pages in use: 9317 (37268 kB virtual memory, total 56127 kB)
real	0m1,106s
user	0m1,038s
sys	0m0,056s
$ time ./rvlinux -P ../binaries/node -- test.js
Node.js says fibonacci(10) = 55
>>> Program exited, exit code = 0 (0x0)
Runtime: …
```
> Add EBREAK live-patching support, execute JIT-segments undecoded

- lib/libriscv/cpu.cpp
- lib/libriscv/cpu.hpp
Even though it's not fast, it's ~10-30% faster than not doing it
To really speed up JIT-segments we need a new dispatch the produces fast bytecodes on-demand. But it's a lot of effort for ~little gain.
> Use instruction handler caching for JIT-segments

- lib/libriscv/cpu.cpp
- lib/libriscv/cpu.hpp
- lib/libriscv/cpu_dispatch.cpp
- lib/libriscv/cpu_inaccurate_dispatch.cpp
- lib/libriscv/decoded_exec_segment.hpp
- lib/libriscv/decoder_cache.cpp
- lib/libriscv/memory.hpp
- lib/libriscv/memory_inline.hpp
This is the fast-path version of yesterdays work, where JIT segments finally get to use the normal dispatch It also reduces and simplifies the overall code. Deleting slow code feels good.
No benefit has been seen from using libtcc or binary translation, even in the background
I suspect that my test programs are not generating the best possible code either. We'll see.
> Just-in-time evict and reprocess JIT-segments

- lib/libriscv/tr_emit.cpp
A modern compiler produces stellar code from just loads and stores, but simpler ones like TCC require some hints.
```
$ VERBOSE=1 ./rvlinux -v ~/github/coremark/coremark-rv32g_b 
* Loading program of size 75145 from 0x777405efb000 to virtual 0x10000 -> 0x22589
* Program segment readable: 1 writable: 0  executable: 1
* Loading program of size 1864 from 0x777405f0d58c to virtual 0x2358c -> 0x23cd4
* Program segment readable: 1 writable: 1  executable: 0
libriscv: No embedded translation found for hash 9C111F55
libriscv: Emitted 17963 accelerated instructions, 13 blocks and 1871 functions. GP=0x23FF8
libriscv: Activated libtcc binary translation with 13/1871 mappings
* Entry is at 0x109f4
2K performance run parameters for coremark.
CoreMark Size    : 666
Total ticks      : 15768
Total time …
```
> Libtcc basic register allocation

- lib/libriscv/cpu.hpp
- lib/libriscv/decoder_cache.cpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
- lib/libriscv/tr_types.hpp
- lib/libriscv/types.hpp
By allowing codegen to run in the background thread, startup time is again reduced a little bit when using binary translation
> bintr: Separate codegen into its own function

- emulator/src/main.cpp
- emulator/src/settings.hpp
- lib/libriscv/common.hpp
- lib/libriscv/cpu_inaccurate_dispatch.cpp
- lib/libriscv/decoded_exec_segment.hpp
- lib/libriscv/decoder_cache.cpp
- lib/libriscv/machine.hpp
- lib/libriscv/memory.hpp
- lib/libriscv/tr_translate.cpp
The binary translator sometimes misses jump locations, however we can record and use them in order to understand the impact
> bintr: Add recording and using of slow-path locations to file

- lib/libriscv/decoder_cache.cpp
- lib/libriscv/linux/syscalls_mman.cpp
- lib/libriscv/memory.cpp
- lib/libriscv/memory.hpp
- lib/libriscv/memory_rw.cpp
- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_translate.cpp
- tests/unit/CMakeLists.txt
General address and function labels are truncated to 64-bit (in the binary translator) which may cause interpreter speed for 128-bit programs that reside in high memory
> Add binary translation support to 128-bit RISC-V

- lib/libriscv/bytecode_impl.cpp
- lib/libriscv/cpu.hpp
- lib/libriscv/debug.cpp
- lib/libriscv/decoder_cache.cpp
- lib/libriscv/decoder_cache.hpp
- lib/libriscv/rv128i.cpp
- lib/libriscv/rv32i.cpp
- lib/libriscv/rv64i.cpp
- lib/libriscv/tr_translate.cpp
This commit attempts to avoid zeroing the decoder cache, and decodes slow-path instructions only when needed
> Reduce overall loading times

- README.md
- lib/libriscv/machine.hpp
- lib/libriscv/machine_inline.hpp
- lib/libriscv/machine_vmcall.hpp
- tests/unit/vmcall.cpp
I'm treating this as a footgun, as I got hit by this recently. The solution is to just add full support for enums in all places where we use template types.
> Add support for enums in system call arguments, results and vmcalls

- lib/libriscv/linux/syscalls_mman.cpp
- lib/libriscv/linux/system_calls.cpp
`MAP_ANONYMOUS` and `MAP_NORESERVE` are already defined when building on macos, but they have different values so the compilation fails. There was a similar issue with `SA_ONSTACK` which is also already defined (with a different value).
> Fix compilation on macos

- lib/libriscv/cpu.cpp
- lib/libriscv/cpu.hpp
- lib/libriscv/decode_bytecodes.cpp
- lib/libriscv/decoder_cache.cpp
- lib/libriscv/instruction_list.hpp
- lib/libriscv/threaded_rewriter.cpp
This improved loading times of some programs by as much as ~5%
This change is currently being fuzzed
> Optimize decoder cache generation by installing ebreaks last phase

- emulator/src/main.cpp
- lib/libriscv/cpu.cpp
- lib/libriscv/machine.cpp
- lib/libriscv/machine.hpp
- lib/libriscv/machine_inline.hpp
This saves 104 bytes per machine, and still allows many strategies for sharing options between machines.
> Allow storing shared options in Machine, optionally

- lib/libriscv/bytecode_impl.cpp
- lib/libriscv/tailcall_dispatch.cpp
- lib/libriscv/threaded_bytecode_array.hpp
- lib/libriscv/threaded_bytecodes.hpp
- lib/libriscv/threaded_rewriter.cpp
This bytecode is from an old, forgotten time
> Remove unused RV32C_BC_JUMPFUNC bytecode

- binaries/show_instructions.sh
- lib/libriscv/bytecode_impl.cpp
- lib/libriscv/decode_bytecodes.cpp
- lib/libriscv/tailcall_dispatch.cpp
- lib/libriscv/threaded_bytecode_array.hpp
- lib/libriscv/threaded_bytecodes.hpp
- lib/libriscv/threaded_rewriter.cpp
These instructions are showing more usage compared to before, so add them to fast-path
> Add bytecodes for C.ADD and C.OR

- lib/libriscv/common.hpp
- lib/libriscv/tr_translate.cpp
This makes it possible to avoid the local filesystem and just get the translated program directly as a string of freestanding C99.
> Add support for binary translation to string

- lib/libriscv/cpu_dispatch.cpp
- lib/libriscv/cpu_inaccurate_dispatch.cpp
- lib/libriscv/tailcall_dispatch.cpp
- lib/libriscv/threaded_rewriter.cpp
I spent quite a lot of time hunting ghosts on this one!
Turns out the syscall table is being looked up incorrectly.
> Fix invalid syscall invocation

- lib/libriscv/elf.hpp
- lib/libriscv/machine.cpp
This fixes an issue with musl libc that uses PT_PHDR in order to find the image base. It's now possible to handle C++ exceptions with musl+libc++.
> Don't push pre-loaded program headers on the stack

- .github/workflows/zig_unittests.yml
- tests/unit/basic.cpp
- tests/unit/basic32.cpp
- tests/unit/brutal.cpp
- tests/unit/custom.cpp
- tests/unit/dynamic.cpp
- tests/unit/examples.cpp
- tests/unit/memory_trap.cpp
- tests/unit/native.cpp
- tests/unit/protections.cpp
- tests/unit/scripts/find_compiler.sh
- tests/unit/va_execute.cpp
- tests/unit/vmcall.cpp
One brutal test and all 32-bit tests are disabled, dealing with multi-threading. Threads are still not supported on musl, but the rest should pass.
> Add Zig toolchain support for unit tests

- emulator/src/main.cpp
- lib/libriscv/tr_emit.cpp
I cannot see how this will ever work since jumps backwards won't undo tracked values. Remove for now.
This was only ever used when register caching was also used, so only with libtcc.
> Remove binary translation register tracking (for now)

- Dockerfile
- lib/CMakeLists.txt
- lib/config.h.in
- lib/libriscv/tr_emit.cpp
- lib/libriscv/tr_tcc.cpp
- lib/libriscv_libtcc.pc.in
- lib/libriscv_libtcc_distro.pc.in
This is an attempt at simplifying TCC code generation by creating custom build scripts for it that pulls and only builds libtcc. The previous libtcc-cmake repository is overly complex.
> Simplify TCC build script

- docs/INTEGRATION.md
- emulator/src/main.cpp
- lib/CMakeLists.txt
- lib/libriscv/common.hpp
- lib/libriscv/machine.cpp
- lib/libriscv/machine.hpp
- lib/libriscv/machine_vmcall.hpp
This feature would never work correctly when the machine was being timed out during a C++ exception, or any other complex procedure
> Remove experimental timed VM calls

- lib/libriscv/common.hpp
- lib/libriscv/cpu.cpp
- lib/libriscv/cpu.hpp
- lib/libriscv/cpu_inline.hpp
- lib/libriscv/decoder_cache.cpp
- lib/libriscv/machine.cpp
- lib/libriscv/memory.cpp
- lib/libriscv/memory.hpp
- lib/libriscv/memory_inline.hpp
- lib/libriscv/multiprocessing.cpp
- lib/libriscv/page.hpp
- lib/libriscv/serialize.cpp
- lib/libriscv/tr_translate.cpp
This commit removes the unused CPU id, slow-path cpu page cache, current_exception (libtcc-only), and places execute segments in a dynamic std::vector.
The slow-path CPU page cache was used by read_next_instruction(), however it can be placed on the stack for precise simulation and passed as an argument.
Making execute segments fully dynamic means we can have as many JIT segments as needed. But there is currently no way to increase this limit outside of changing a global define. Perhaps it should become a MachineOptions setting?
Casual measurements show that this change saves 256 bytes on 32-bit.
> Trim the size of the Machine structure a bit

- lib/libriscv/win32/system_calls.cpp
This fixes a startup issue with musl-libc++ on Windows hosts
musl calls ppoll on certain fd's and writes to zero if ppoll returns non-zero
> Stub ppoll on Windows, returning 0

- lib/libriscv/rsp_server.hpp
The probably most annoying part of windows/linux crossplatform development.
long int vs long long int..
Example if in `handle_readmem` we get `buffer = "m7fff54c10000,1"`
Old code, when compiled on windows with clang-cl, will read `addr = 0x54c10000` because `%lx` is 32bit.
After this fix, it will use `%lx` on linux (reading 64bit) and `%llx` on windows (reading 64bit).
I have NOT tested this on linux, but the macros I use are standard C so they should be fine?
There are probably more issues like that.
For example for my build to work, I need to comment out `#include <unistd.h>` on windows.
I think it should check and only include it on linux, but you'll know better what it's purpose is.
And also, the `SOCK_NONBLOCK` block at the top doesn't work, it just makes gdb instantly disconnect. …
> Fix RSP Server using wrong format spec for 64bit variables on Win

- .github/workflows/zig_unittests.yml
- lib/libriscv/common.hpp
- lib/libriscv/machine.hpp
- lib/libriscv/memory.hpp
- lib/libriscv/registers.hpp
- lib/libriscv/tr_api.cpp
- lib/libriscv/tr_translate.cpp
This PR makes it possible to configure the general alignments of all libriscv structures. It will fail to compile if V-extension is enabled and the V-extension alignment is higher than the general alignment.
> Use RISCV_MACHINE_ALIGNMENT macro to configure alignments

- lib/libriscv/rvf_instr.cpp
- lib/libriscv/tr_emit.cpp
Also, properly implement FCVT.D.W[U] and FCVT.D.L[U] in binary translator
I really thought I had solved these issues, but clearly not. I had a ghost in my machine with some coordinates not printing properly when converting an int to float, and what do you know: The float was loaded from memory and contained the right value, but somehow the instructions leading to the print failed. The only way it could be so was an emulation bug. Now fixed! Will try to create a test for this later.
So, how could this bug slip away for so long? Well, it's because when you convert an integer to a float, you usually have an integer. Not a 64-bit value, just a 32-bit value that makes sense to convert to a 32-bit float. But, what if you had a 2x packed 32-bit integers as part of a calling convention, that got …
> Fix conversion issue with FCVT.S.W and FCVT.S.WU

- lib/libriscv/decoded_exec_segment.hpp
- lib/libriscv/tr_translate.cpp
It's not fully working yet, but the problematic parts have been disabled, leaving it in a state of working but not very effective. It won't be able to improve all programs, as many jump targets are skipped.
This PR solves the background waiting issue as well.
> Improve background binary translation

- .github/workflows/buildconfig.yml
- .github/workflows/unittests.yml
- .github/workflows/unittests_exp.yml
- .github/workflows/unittests_threaded.yml
- emulator/src/main.cpp
- lib/CMakeLists.txt
- lib/libriscv/common.hpp
- lib/libriscv/memory.cpp
- lib/libriscv/tailcall_dispatch.cpp
- lib/libriscv/tr_translate.cpp
The JIT has been tested on:
- Windows
- Linux
- Android
- macOS
The first commit probably stopped testing the base interpreter, so that has to be enabled again, but it will be interesting to see if the initial commit can pass all the tests regardless!
> Make JIT default, with live-patching enabled
