libriscv/libriscv

lib/CMakeLists.txt, lib/libriscv/cpu.hpp, lib/libriscv/decoder_cache.cpp, lib/libriscv/decoder_rewriter.cpp
Rewrites all branch instructions to faster variants, as long as certain conditions are met.
=> Initial rewrite decoder work

lib/libriscv/decoder_rewriter.cpp, lib/libriscv/instr_decoding.inc, lib/libriscv/registers.hpp, lib/libriscv/rvi_instr.cpp
Also, align registers again in the hopes of getting some autovec going
=> Rewrite stype and jtype

lib/libriscv/cpu.cpp, lib/libriscv/cpu.hpp, lib/libriscv/decoder_cache.cpp, lib/libriscv/fastsim.hpp, lib/libriscv/memory.cpp, lib/libriscv/serialize.cpp
Improves fastsim enough to be reliable, however it needs tweaking to have good default settings.
=> Several fixes and improvements to fast simulator mode

README.md, lib/libriscv/cpu.cpp
I also tried to document what computer was used to measure MIPS and CoreMark
=> Minor improvements to fastsim

lib/libriscv/cpu.cpp, lib/libriscv/decoder_rewriter.cpp
An all around improvement for the most used instruction (ADDI), as well as streamlining 4 instructions at a time using fastsim
=> Make ADDI faster using decoder rewrites

lib/CMakeLists.txt, lib/libriscv/bytecode_impl.cpp, lib/libriscv/cpu.hpp, lib/libriscv/cpu_dispatch.cpp, lib/libriscv/tailcall_dispatch.cpp, lib/libriscv/threaded_bytecodes.hpp, lib/libriscv/threaded_dispatch.cpp, lib/libriscv/types.hpp
It has not shown to be much faster than computed goto, and is rather disappointing
=> Implement experimental tailcall dispatch

lib/libriscv/linux/system_calls.cpp, lib/libriscv/rsp_server.hpp
This lets us build libriscv with most Linux system calls on FreeBSD
=> FreeBSD build support

lib/libriscv/common.hpp, lib/libriscv/tr_api.cpp, lib/libriscv/tr_api.hpp, lib/libriscv/tr_emit.cpp, lib/libriscv/tr_translate.cpp
Manipulate instruction counter directly in translation code
Also solves some issues with setting the correct PC for system functions in binary translation
=> Simplify instruction counting in binary translation

docs/VMCALL.md, lib/CMakeLists.txt, lib/libriscv/cpu.cpp, lib/libriscv/cpu.hpp, lib/libriscv/cpu_dispatch.cpp, lib/libriscv/debug.cpp, lib/libriscv/machine.hpp, lib/libriscv/machine_inline.hpp, lib/libriscv/machine_vmcall.hpp, lib/libriscv/native_threads.cpp, lib/libriscv/prepared_call.hpp, lib/libriscv/tailcall_dispatch.cpp, tests/unit/examples.cpp
Also, implement an initial version of PreparedCall
=> Pass PC as register to simulate() and next_exec_seg()

lib/libriscv/bytecode_impl.cpp, lib/libriscv/cpu.cpp, lib/libriscv/cpu.hpp, lib/libriscv/cpu_dispatch.cpp, lib/libriscv/cpu_inline.hpp, lib/libriscv/debug.cpp, lib/libriscv/decoder_cache.hpp, lib/libriscv/machine.hpp, lib/libriscv/memory.cpp, lib/libriscv/memory.hpp, lib/libriscv/memory_helpers_paging.hpp, lib/libriscv/memory_inline.hpp, lib/libriscv/memory_rw.cpp, lib/libriscv/serialize.cpp, lib/libriscv/tailcall_dispatch.cpp
This PR is an attempt at stabilizing performance. The emulator clearly has alignment issues, and the performance changes wildly with code changes.
=> Reorganize members, add alignment hints, move atomics to Memory

binaries/newlib64/src/hello_world.cpp, c/README.md, c/libriscv.cpp, c/libriscv.h, c/test/test.c
This exposes enough functionality to craft low-latency VM function calls. It should be interesting to benchmark them.
=> Add C API functions related to VM calls

lib/libriscv/cpu.cpp, lib/libriscv/cpu.hpp, lib/libriscv/decoded_exec_segment.hpp, lib/libriscv/machine.cpp, lib/libriscv/tr_emit.cpp, lib/libriscv/tr_translate.cpp, tests/unit/brutal.cpp
An effort to make the last, brutal test pass. And also some general improvements.
=> Binary translation improvements

examples/gamedev/example.cpp, examples/gamedev/script_program/program.cpp, lib/libriscv/common.hpp, lib/libriscv/machine_inline.hpp
=> Add support for std::span for system call arguments

README.md, lib/libriscv/bytecode_impl.cpp, lib/libriscv/cpu_dispatch.cpp, lib/libriscv/decoder_cache.cpp, lib/libriscv/rv32i_instr.hpp, lib/libriscv/tr_api.cpp, lib/libriscv/tr_emit.cpp, lib/libriscv/tr_emit_rvc.cpp, lib/libriscv/tr_translate.cpp, lib/libriscv/tr_types.hpp
This is part of the work towards supporting binary translation with the C-extension enabled
=> Support RVC in binary translation

.github/workflows/bintr.yml
Binary translation used to be verified manually, however with the support of C-extension, it's now possible to verify automatically with simple tests.
=> Add binary translation tests

lib/libriscv/cpu_dispatch.cpp
This also resulted in a tiny improvement for translated loops leaving and entering another
=> bintr: Add short-circuit for initial function

lib/libriscv/decode_bytecodes.cpp, lib/libriscv/decoded_exec_segment.hpp, lib/libriscv/decoder_cache.cpp, lib/libriscv/tr_tcc.cpp, lib/libriscv/tr_translate.cpp
Also solve some confusion around how the bytecode gets applied
=> bintr: Add validation step to binary translation mappings

emulator/src/main.cpp, lib/libriscv/common.hpp, lib/libriscv/memory.cpp
=> Add option to disable .text section segment reduction

lib/libriscv/cpu_dispatch.cpp, lib/libriscv/cpu_inaccurate_dispatch.cpp, lib/libriscv/decoder_cache.hpp, lib/libriscv/tr_translate.cpp
It's now able to live-patch and apply the transitional bytecodes
=> bintr: Fix some bugs in live patching

.github/workflows/buildconfig.yml, lib/CMakeLists.txt, lib/libriscv/linux/syscalls_poll.cpp, lib/libriscv/linux/system_calls.cpp
Needs to restore and have some review.
=> Add macos.

lib/libriscv/tr_translate.cpp
This makes it possible to load binary translations in a straight-forward manner.
=> bintr: Simplify loading of embedded and shared binary translations

emulator/src/main.cpp, lib/libriscv/linux/syscalls_mman.cpp, lib/libriscv/linux/system_calls.cpp
=> Proxy mode

lib/libriscv/linux/syscalls_mman.cpp, lib/libriscv/memory_rw.cpp, lib/libriscv/native_threads.cpp, lib/libriscv/posix/threads.cpp, lib/libriscv/rva.hpp, lib/libriscv/rva_instr.cpp, lib/libriscv/threads.hpp
Also, simplify LR/SC atomic operations and make it easier to disable atomics.
=> More futex work

emulator/src/main.cpp, emulator/src/newlib_open.hpp, lib/libriscv/linux/system_calls.cpp, lib/libriscv/machine.hpp, lib/libriscv/win32/system_calls.cpp
Adds basic open through system call 1024
=> Allow opening a file with Newlib emulator

lib/libriscv/tr_emit.cpp, lib/libriscv/tr_translate.cpp
Small improvements to try to reduce latency of register caching
=> bintr: Improve system call register caching

lib/libriscv/tr_emit.cpp, tests/unit/serialize.cpp
A scary implementation that could result in weird behavior when people want to modify registers outside of A0-A7 in system calls, but only when libtcc is enabled with register caching. It greatly reduces latency of most system calls.
=> bintr: Reduce register usage during most system calls

.github/workflows/emulator.yml, README.md, examples/doom/CMakeLists.txt, examples/doom/build.sh
=> Add noexcept emulator to GH actions

lib/libriscv/linux/system_calls.cpp, lib/libriscv/posix/threads.cpp
This fixes a problem with running Rust programs, as well as getting back ability to run NodeJS
=> Unblock futex waiter if a deadlock would occur

lib/libriscv/bytecode_dispatch.cpp, lib/libriscv/bytecode_impl.cpp, lib/libriscv/cpu_dispatch.cpp, lib/libriscv/cpu_inaccurate_dispatch.cpp, lib/libriscv/debug.cpp, lib/libriscv/decoded_exec_segment.hpp, lib/libriscv/decoder_cache.cpp, lib/libriscv/tailcall_dispatch.cpp, lib/libriscv/threaded_rewriter.cpp
This change live-patches syscall invocations that only handle one system call to become faster
=> Live-patch system calls that only handles a single number to be faster

lib/libriscv/cpu.hpp, lib/libriscv/machine.hpp, lib/libriscv/tr_api.cpp, lib/libriscv/tr_translate.cpp, lib/libriscv/util/crc32c.cpp
This makes it possible to share the embeddable code with multiple platforms
=> Pass arena and counter offsets to binary translation at run-time

lib/libriscv/debug.cpp, lib/libriscv/debug.hpp, lib/libriscv/machine.cpp, lib/libriscv/machine.hpp, lib/libriscv/machine_inline.hpp, lib/libriscv/rsp_server.hpp
This reduces the size of Machine by at least 8 bytes
=> Move debug_printer into DebugMachine and RSPClient

lib/libriscv/tr_tcc.cpp
We will have to do the same on macOS perhaps?
=> Add system include path for TCC on Linux

lib/libriscv/linux/system_calls.cpp, lib/libriscv/win32/epoll.cpp, lib/libriscv/win32/system_calls.cpp
Not enough to run NodeJS on Windows, but it gets all the way into epoll-related stuff which must be emulated properly
=> Implement and stub a bunch of system calls on Windows

lib/libriscv/decoder_cache.cpp, lib/libriscv/decoder_cache.hpp, lib/libriscv/tr_translate.cpp
A rare optimization that improves instruction counting performance
=> Simplify C-ext icount
